### ISSUE TITLE
Fix the styling on your branch

### ISSUE THREAD

**Issue by briannededeugd** [briannededeugd/tumimundo#34]
Hi all,

Very unfortunate that the style was buggy when we showed the prototype to the client, but the issue was found: a missing closing curly bracket in the `style.css` 🥴 I've directly fixed this (as well as a responsiveness issue) on the main branch, so before you continue on your feature, make sure to switch to the main branch in VSCode, do `git pull`, then go to the branch you're working on and do `git merge main`. All should be fixed after that!

We've got this (as we always do) 🏎️💨

**Comment by rosemulazada** [comment]
Always something ridiculously small like this that breaks your entire app.. _the second before presenting to the client._ We picked it up nicely nonetheless. :D

**Comment by briannededeugd** [comment]
I guess everyone has done this? Closing the issue now.
